project=Cerberus Winlator
versionName=0.2.0-ENGINE-1
versionCode=3
applicationId=com.cerberus.winlator
upstream=BrunoDev Winlator 11.2
upstreamCommit=4f55d117fff1542944e5b91f433470445160ce08
profile=ENGINE-1
engine=ENGINE-1
engineMode=read-only
